### PR TITLE
avoid uncoverable code by not using gemspec in Gemfile

### PR DESCRIPTION
**Pull request by grosser**
... alternative approach to make code coverage work

### CODE REVIEW

**Comment by ddnexus** [comment]
Rubocop seems a bit too picky!

**Comment by ddnexus** [comment]
I like moving the dev gems into the Gemfile! Any drawback?

**Comment by grosser** [comment]
fixed rubocop

no drawbacks unless there were any runtime dependencies, then it would duplicate the gemspec ... but I don't think there will ever be runtime dependencies ...

**Comment by grosser** [comment]
merge 32 and I'll rebase it

**Comment by grosser** [comment]
rebased and ready!

**Pull request merged**
