### PR TITLE
Add: locales: zh-CN, zh-HK, zh-TW 

### PR DESCRIPTION
**Pull request by Davidzhu001**
I update the locale file of those three languages

### CODE REVIEW

**Comment by Davidzhu001** [comment]
#610

**Comment by benkoshy** [comment]
Thank you - your contribution is much appreciated.

Here is what I have checked / verified:

### Step 1: Check the pluralization in rails-i18n and note it down.

- [x] zh-cn pluralisation is [other](https://github.com/svenfuchs/rails-i18n/blob/master/rails/pluralization/zh-CN.rb). 
- [x] zh-hk pluralisation is [other](https://github.com/svenfuchs/rails-i18n/blob/master/rails/pluralization/zh-HK.rb)
- [x] zh-tw pluralisation is [other](https://github.com/svenfuchs/rails-i18n/blob/master/rails/pluralization/zh-TW.rb)

All of the pluralization rules. are `other`.

### Step 2: Check that pagy defines `other`

- [x] [Yes](https://github.com/ddnexus/pagy/blob/2ad6ddbedd6f8daaee6fba69235803634c6e2f9a/gem/lib/pagy/i18n.rb#L67) it does. We do not need to define `other` because it is already there.

### Step 3: Add an entry to the [locales hash](https://github.com/ddnexus/pagy/blob/master/gem/lib/pagy/i18n.rb#L95C1-L115)

- [x] Yes. This is done I see it in the PR:

```rb
                 hash['zh-CN'] = RULE[:other]
                 hash['zh-HK'] = RULE[:other]
                 hash['zh-TW'] = RULE[:other]
```

### Step 4: Check all the .yml files for the correct entries:

I have made some modifications I will push them shortly.

- [ ] All the `nav` entries default to 'other'. (Please confirm whether this is correct.)

**Comment by benkoshy** [comment]
I could do not have permission to push, I recreated a branch here: 

https://github.com/ddnexus/pagy/tree/chinese-locales

Please review / feel free to cherry-pick and overwrite those commits with your name.

**Comment by Davidzhu001** [comment]
I checked this branch https://github.com/ddnexus/pagy/tree/chinese-locales.
It seems you already added the translation and fixed it. 

Should I close the pull request or what should I do next?

**Comment by benkoshy** [comment]
> I checked this branch https://github.com/ddnexus/pagy/tree/chinese-locales. It seems you already added the translation and fixed it.
> 
> Should I close the pull request or what should I do next?

- What should you do next? 
- (i) Cherry pick those commits onto your branch. 
- (ii) attribute yourself as the author by amending those commits  `git commit --amend --author "Davidzhu001 <davids_email@put_it_here.com>"`
- and just double check that all the entries are correct and make sense. e.g. the nav entries I have defaulted to read as the `other` keys, rather than `single`.

**Comment by benkoshy** [comment]
@Davidzhu001 I have pushed onto your master branch and attributed you as author via your previously signed commits. There is nothing more you need to do. Thank you for your contribution.

@ddnexus ready for merging, subject to your review.

**Comment by Davidzhu001** [comment]
Thanks so much, i was little busy this week. sorry for the late response

**Pull request merged**
