### PR TITLE
docs: add foundation image

### PR DESCRIPTION
**Pull request by benkoshy**
### What is this?

* add the foundation pagination image to the docs.
* 10 px margin.

demo

### What's missing

* foundation_combo_nav image - because it doesn't seem to come out right: using the latest version of foundation seems to have changed things:

foundation_combo_nav

Perhaps we would have to work out how to manage versioning for foundation?

### Why?

User experience.

### CODE REVIEW

**Comment by ddnexus** [comment]
Please, try to add `white-space: nowrap;` style from:
```
        }<span class="input-group-label">#{pagy_t 'pagy.combo_nav_js', page_input: input, count: p_page, pages: p_pages}</span>#{
```
to:
```
        }<span class="input-group-label" style="white-space: nowrap;">#{pagy_t 'pagy.combo_nav_js', page_input: input, count: p_page, pages: p_pages}</span>#{
```

**Comment by benkoshy** [comment]
> Please, try to add `white-space: nowrap;` style from:
> 
> ```
>         }<span class="input-group-label">#{pagy_t 'pagy.combo_nav_js', page_input: input, count: p_page, pages: p_pages}</span>#{
> ```
> 
> to:
> 
> ```
>         }<span class="input-group-label" style="white-space: nowrap;">#{pagy_t 'pagy.combo_nav_js', page_input: input, count: p_page, pages: p_pages}</span>#{
> ```
> 
> in `lib/pagy/extras/foundation.rb:62`

* Appreciate the advice:  fixing the combo-nav is not a problem.
* My question is a general question of policy: how to handle the upgrading of css frameworks? (I don't think anyone has complained so far, which is interesting btw).

**Comment by ddnexus** [comment]
> how to handle the upgrading of css frameworks?

**Comment by ddnexus** [comment]
> how to handle the upgrading of css frameworks?

Try to solve eventual issues with the most compatible solution, as we did with bootstrap, which is:

1. use a specific framework class when possible
2. use regular inline css when it's not
3. keep compatibility with the highest versions of the framework without breaking the version supported when the current pagy mayor version started (x.0.0)

**Comment by benkoshy** [comment]
> Please, try to add white-space: nowrap; style from:
> 
>         }<span class="input-group-label">#{pagy_t 'pagy.combo_nav_js', page_input: input, count: p_page, pages: p_pages}</span>#{
> 
> to:
> 
>         }<span class="input-group-label" style="white-space: nowrap;">#{pagy_t 'pagy.combo_nav_js', page_input: input, count: p_page, pages: p_pages}</span>#{
> 

The suggested solution did not solve the combo-nav problem. 

I will have to return to solve the combo-nav problem. However, feel free to merge as-is.

**Comment by benkoshy** [comment]
@ddnexus   Try this markup:


```html

<!-- Compressed CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/css/foundation.min.css" crossorigin="anonymous">

<!-- Compressed JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/js/foundation.min.js" crossorigin="anonymous"></script>


<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foundation for Sites</title>
  </head>
  <body>

    <!-- Pagy foundation nav -->
<div class="input-group" data-pagy="WyJjb21ibyIsIlx1MDAzY2EgaHJlZj1cIi9mb3VuZGF0aW9uX21vdmllcz9wYWdlPV9fcGFneV9wYWdlX19cdTAwMjZhbXA7aXRlbXM9MjBcIiAgIHN0eWxlPVwiZGlzcGxheTogbm9uZTtcIlx1MDAzZVx1MDAzYy9hXHUwMDNlIl0=">
<a style="margin-bottom: 0" class="prev button primary disabled" href="#">‹&nbsp;Prev</a><span class="input-group-label" style="white-space: nowrap;"><label>Page <input class="input-group-field cell shrink" type="number" min="1" max="168" value="1" style="width: 4rem; padding: 0 0.3rem; margin: 0 0.3rem;"> of 168</label></span><a href="/foundation_movies?page=2&amp;items=20" rel="next" style="margin-bottom: 0" aria-label="next" class="next button primary">Next&nbsp;›</a>
</div>
    
    
  </body>
</html>




```

**Comment by benkoshy** [comment]
Try this: https://jsfiddle.net/#&togetherjs=kD7qijHM2l

**Comment by ddnexus** [comment]
OK, I've got a fix for the ruby helper, which is adding the `style = "display: contents;"` to the plain `<label>`  provided by the dictionary.

Here is the modified helper:

```ruby
    # Javascript combo pagination for Foundation: it returns a nav and a JSON tag used by the pagy.js file
    def pagy_foundation_combo_nav_js(pagy, pagy_id: nil, link_extra: '')
      p_id    = %( id="#{pagy_id}") if pagy_id
      link    = pagy_link_proc(pagy, link_extra: link_extra)
      p_page  = pagy.page
      p_pages = pagy.pages
      input   = %(<input class="input-group-field cell shrink" type="number" min="1" max="#{
                    p_pages}" value="#{p_page}" style="width: #{
                    p_pages.to_s.length + 1}rem; padding: 0 0.3rem; margin: 0 0.3rem;">)

      %(<nav#{p_id} class="pagy-foundation-combo-nav-js" aria-label="Pagination"><div class="input-group" #{
          pagy_data(pagy, :combo, pagy_marked_link(link))}>#{
          if (p_prev  = pagy.prev)
            link.call p_prev, pagy_t('pagy.nav.prev'),
                      'style="margin-bottom: 0" aria-label="previous" class="prev button primary"'
          else
            %(<a style="margin-bottom: 0" class="prev button primary disabled" href="#">#{pagy_t 'pagy.nav.prev'}</a>)
          end
        }<span class="input-group-label">#{pagy_t('pagy.combo_nav_js', page_input: input, count: p_page, pages: p_pages)
                                           .sub('<label>', '<label style="display: contents;">')}</span>#{
          if (p_next  = pagy.next)
            link.call p_next, pagy_t('pagy.nav.next'), 'style="margin-bottom: 0" aria-label="next" class="next button primary"'
          else
            %(<a style="margin-bottom: 0" class="next button primary disabled" href="#">#{pagy_t 'pagy.nav.next'}</a>)
          end
        }</div></nav>)
    end
```

If we cannot find a better (i.e. pure CSS) option, that would work.

Please, let me know whether we can find something better. Thanks.

**Comment by benkoshy** [comment]
I'll try for a pure css  option.

In the mean time should we use this as a temporary fix,  till the pure css option is found?

**Comment by ddnexus** [comment]
Either one would require a release. This started as documentation issue, so we should probably create a code issue and after that will be closed, we could complete this one.

**Comment by benkoshy** [comment]
### Pure CSS Solution? 


### Demo:
https://jsfiddle.net/L8ejyht1/6/

### The result
here's how it looks in pagy-rails

### Changes:

```diff
-     <nav class="pagy-foundation-combo-nav-js" aria-label="Pagination">
+    <nav class="pagy-foundation-combo-nav-js" aria-label="Pagination">
         <div class="input-group" data-pagy="WyJjb21ibyIsIlx1MDAzY2EgaHJlZj1cIi9mb3VuZGF0aW9uX21vdmllcz9wYWdlPV9fcGFneV9wYWdlX19cdTAwMjZhbXA7aXRlbXM9Mj
           <a style="margin-bottom: 0" class="prev button primary disabled" href="#">‹&nbsp;Prev</a>
           <span class="input-group-label">
-            <label>Page
+           <label class="flex-container align-middle">
+              <span>Page</span>
               <input class="input-group-field cell shrink" type="number" min="1" max="168" value="1" style="width: 4rem; padding: 0 0.3rem; margin: 0 
-              of 168
+              <span>of 168</span>
             </label>
           </span>
         <a href="/foundation_movies?page=2&amp;items=20" rel="next" style="margin-bottom: 0" aria-label="next" class="next button primary">Next&nbsp;›
       </div>
     </nav>
```

What was changed?

* Made the label a flex container, and force the children to align-middle
* Made all the children span items.


Here's the full markup:

```html
    <nav class="pagy-foundation-combo-nav-js" aria-label="Pagination">
        <div class="input-group" data-pagy="WyJjb21ibyIsIlx1MDAzY2EgaHJlZj1cIi9mb3VuZGF0aW9uX21vdmllcz9wYWdlPV9fcGFneV9wYWdlX19cdTAwMjZhbXA7aXRlbXM9MjBcIiAgIHN0eWxlPVwiZGlzcGxheTogbm9uZTtcIlx1MDAzZVx1MDAzYy9hXHUwMDNlIl0=">
          <a style="margin-bottom: 0" class="prev button primary disabled" href="#">‹&nbsp;Prev</a>
          <span class="input-group-label">
            <label class="flex-container align-middle">
              <span>Page</span>
              <input class="input-group-field cell shrink" type="number" min="1" max="168" value="1" style="width: 4rem; padding: 0 0.3rem; margin: 0 0.3rem;"> 
              <span>of 168</span>
            </label>
          </span>
        <a href="/foundation_movies?page=2&amp;items=20" rel="next" style="margin-bottom: 0" aria-label="next" class="next button primary">Next&nbsp;›</a>
      </div>
    </nav>
```

### Possible issues:
* Have not yet tested the JS (pagy-rails isn't loading JS for some reason which I have to fix).

### Thoughts?

Are there any obvious issues/problems i'm missing?

**Comment by ddnexus** [comment]
I don't get how you changed the helper that produces the markup in order to add the label class.

**Comment by benkoshy** [comment]
> I don't get how you changed the helper that produces the markup in order to add the label class.

Good point. I didn't touch the helper at all, I edited the markup directly without using pagy or ruby. Will there be issues translating it into the helper?

**Comment by ddnexus** [comment]
Oh yes, there is no way you are going to change the label attributes without using ruby, because they come from the dictionary file. 

You just implemented a (probably slightly better) variation of my previous proposal, which indeed still involves the ruby manipulation of the string coming from the dictionary.

**Comment by benkoshy** [comment]
> Oh yes, there is no way you are going to change the label attributes without using ruby, because they come from the dictionary file.
> 
> You just implemented a (probably slightly better) variation of my previous proposal, which indeed still involves the ruby manipulation of the string coming from the dictionary.

In that case: let's adopt your proposal. I can submit a PR for that, and fix the docs at the same time. Any objections to this?

**Comment by ddnexus** [comment]
Using `class` instead of `style` is better IMO.

**Comment by ddnexus** [comment]
Just to clarify. 

When I said that "there is no way you are going to change the label attributes without using ruby", I didn't mean that it's impossible to produce the desired layout in pure CSS. it"s just impossible if you need to modify the `label` attributes.

The possible alternative to investigate is achieving the same by modifying the way we generate the *container* of the label, in such a way that we can use the label as it comes from the dictionary string. 

We might be able to do so ether by using some class on it or changing the way we produce the combo all together.

**Comment by benkoshy** [comment]
> Could not make it work without applying a class on the label:

```html
<label class="flex-container align-middle" ... />
```

The above works nicely.

As a result I will adopt your suggestion approach.

**Comment by ddnexus** [comment]
I've got a new version that actually reduces the markup a bit, so it's a bit better than the other two.

Here is the result:

```html
<nav class="pagy-foundation-combo-nav-js" aria-label="Pagination"><div class="input-group" data-pagy="WyJjb21ibyIsIjxhIGhyZWY9XCJodHRwOi8vd3d3LmV4YW1wbGUuY29tL3N1YmRpcj9wYWdlPV9fcGFneV9wYWdlX19cIiAgIHN0eWxlPVwiZGlzcGxheTogbm9uZTtcIj48L2E+Il0="><a style="margin-bottom: 0" class="prev button primary disabled" href="#">&lsaquo;&nbsp;Prev</a><label class="input-group-label">Page <input class="input-group-field cell shrink" type="number" min="1" max="168" value="1" style="width: 4rem; padding: 0 0.3rem; margin: 0 0.3rem;"> of 168</label><a href="http://www.example.com/subdir?page=2"   rel="next" style="margin-bottom: 0" aria-label="next" class="next button primary">Next&nbsp;&rsaquo;</a></div></nav>
```

If we don't find anything better, we can go with this one.
Pushed [here](https://github.com/ddnexus/pagy/compare/dev..foundation-combo).

**Comment by benkoshy** [comment]
> I've got a new version that actually reduces the markup a bit, so it's a bit better than the other two.
> 
> Here is the result:
> 
> ```
> <nav class="pagy-foundation-combo-nav-js" aria-label="Pagination"><div class="input-group" data-pagy="WyJjb21ibyIsIjxhIGhyZWY9XCJodHRwOi8vd3d3LmV4YW1wbGUuY29tL3N1YmRpcj9wYWdlPV9fcGFneV9wYWdlX19cIiAgIHN0eWxlPVwiZGlzcGxheTogbm9uZTtcIj48L2E+Il0="><a style="margin-bottom: 0" class="prev button primary disabled" href="#">&lsaquo;&nbsp;Prev</a><label class="input-group-label">Page <input class="input-group-field cell shrink" type="number" min="1" max="168" value="1" style="width: 4rem; padding: 0 0.3rem; margin: 0 0.3rem;"> of 168</label><a href="http://www.example.com/subdir?page=2"   rel="next" style="margin-bottom: 0" aria-label="next" class="next button primary">Next&nbsp;&rsaquo;</a></div></nav>
> ```
> 
> If we don't find anything better, we can go with this one. Pushed [here](https://github.com/ddnexus/pagy/compare/dev..foundation-combo).

In that case, why not run with that version? We could keep searching, but I do not think the costs would outweigh the benefits.

**Comment by ddnexus** [comment]
> I do not think the costs would outweigh the benefits

You are right. 

If you want you can use that branch, add the commits for fixing the tests and e2e and create a PR.

**Comment by benkoshy** [comment]
This should be ready to merge now.

**Comment by ddnexus** [comment]
Thank you!

**Pull request merged**
