### PR TITLE
Rename Swedish locale to sv.yml

### PR DESCRIPTION
**Pull request by davidwessman**
- The Swedish locale is referred to as sv in the I18n-gem:
  https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/sv.yml
- It can also be referred to as sv_SE.

### CODE REVIEW

**Comment by davidwessman** [comment]
I decided to rename it completely, but feel free to keep the old file for backwards compatibility if that is needed.

**Comment by ddnexus** [comment]
I think we should have a `sv.yml` containing the `sv` key and a `sv-SE.yml` containing `sv-SE`,  since they are also in the official i18n gem. We used the same file/key naming for the `zn-CH`, `zn-HK` and the `zn-TW`.

Please, could you modify the PR accordingly?

**Comment by davidwessman** [comment]
> I think we should have a `sv.yml` containing the `sv` key and a `sv-SE.yml` containing `sv-SE`, since they are also in the official i18n gem. We used the same file/key naming for the `zn-CH`, `zn-HK` and the `zn-TW`.
> 
> Please, could you modify the PR accordingly?

Done!

**Comment by ddnexus** [comment]
Thank you. I will add the needed changes for pluralization and deprecation.

**Pull request merged**
