### PR TITLE
Semantic UI nav helper

### PR DESCRIPTION
**Pull request by mad42**
Helper + Doc

### CODE REVIEW

**Comment by mad42** [comment]
Hello @ddnexus, really nice work on this gem !

I've just added a test file to complete this first contribution.

I'll add the responsive and compact part in few days, i didn't look at the js part yet.
Happy to help :)

**Comment by ddnexus** [comment]
Thank you @mad42.
No need to look at the js part actually. You have just to do the same as you did for the `pagy_nav` but with the `pagy_nav_compact` and `pagy_nav_responsive`, i.e. mostly changing the classes.

For the `compact` you may probably have to change it a bit more, since it is actually a quite custom helper that you have to render in different ways when using different frameworks. For example, with bootstrap I used a few grouped buttons. That could probably be the same with Semantic UI (which has a lot of nice button components).

**Comment by mad42** [comment]
Helpers for `pagy_nav_compact ` and `pagy_nav_responsive ` embed javascript code, i'm using a very restrictive Content Security Policy forbidding inline javascript `:unsafe_inline` so i need to  isolate the javascript part and hook it differently, it will mess with the existing helpers.

What do you think of the approach of taking off js from helpers ?

Cordially,

**Comment by ddnexus** [comment]
All the helpers pass the :unsafe_inline check since the issue #52 has been closed.

**Comment by mad42** [comment]
Good to know that it was handled before :)
(my fault, i didn't look at previous issues)

I'll try to adapt both helpers !

**Comment by ddnexus** [comment]
Thank you @mad42. Looking forward to merge your final PR.

**Comment by ddnexus** [comment]
Hi @mad42,
what is the status of this PR? I may probably have time for it this weekend...

**Comment by ddnexus** [comment]
Commit cherry-picked, added compact and responsive navs and merged.

**Pull request closed without merging**
