### PR TITLE
Add Vietnamese locale

### PR DESCRIPTION
**Pull request by YutoYasunaga**
Thank you for the great project,
I've added Vietnamese locale

**Result:**

スクリーンショット 2023-09-01 21 04 56

スクリーンショット 2023-09-01 21 04 25

スクリーンショット 2023-09-01 21 06 43

スクリーンショット 2023-09-01 21 04 34

### CODE REVIEW

**Comment by benkoshy** [comment]
[YutoYasunaga](https://github.com/YutoYasunaga) thank you for your contribution!

It will take some time for me to assess / understand how locales work etc.

I will get back to you in time.

**Comment by benkoshy** [comment]
Hi Yuto

Thank you for your contribution! Apologies for the delay. 

A couple of things are are required to finalize the merge. (Noted here: https://github.com/ddnexus/pagy/blob/master/lib/locales/README.md)

* We would need to add to the hash here: 
 https://github.com/ddnexus/pagy/blob/e237479042f2a7c1cba99b0c6d508bad00e09284/lib/pagy/i18n.rb#L95

* It looks like you've matched all the keys well which is great! Here is an example in Japanese which uses the "other" pluralization which you've already matched perfectly: https://github.com/ddnexus/pagy/blob/master/lib/locales/ja.yml

**Comment by YutoYasunaga** [comment]
Thank you for your feedback and detailed guidance. apologies for the delay.

I have made the requested changes and updated the pull request. Please review and let me know if there are any further modifications needed.

**Comment by benkoshy** [comment]
thx @YutoYasunaga 

I will review this next week: by the 2023-09-21.

**Comment by benkoshy** [comment]
Thank you for your patience. It looks good to me. I have had a closer look at tested it out on my own repo:

multiple_pages_2
multiple_pages
single_page
zero

The only issue now is working out why the CI is failing. I will try to have a look by tomorrow.

**Comment by ddnexus** [comment]
It's missing the new file in the manifest. You can run the `manifest:update` task and commit.

Which is another point missed in the doc 🤷

**Comment by benkoshy** [comment]
@YutoYasunaga if you run the following command:

```sh
rake manifest:generate
```

and then confirm it with: 

```sh
rake manifest:check
```
You can then add another commit and the CI will pass. Or you can cherry pick this commit:  https://github.com/YutoYasunaga/pagy/commit/68ae38b9dccac57c403a462e775612e9977b7d43

And I think that will be all that is required.

**Comment by YutoYasunaga** [comment]
Thank for your help.

I pushed it already.

**Comment by benkoshy** [comment]
Rubocop is complaining. You can cherry-pick: https://github.com/ddnexus/pagy/commit/ff4cd69f9ffaebdad0d284d993e02de47d257a50

**Comment by YutoYasunaga** [comment]
@benkoshy Thank you. I have done it.

image

**Comment by ddnexus** [comment]
Thank you @YutoYasunaga @benkoshy

**Pull request merged**
