### PR TITLE
Add french localization file

### PR DESCRIPTION
**Pull request by czj**
We would love to use pagy in production on our (French) apps.

We hope this localization will help other teams use this great gem ❤️

### CODE REVIEW

**Comment by ddnexus** [comment]
Thank you for the contribution!
I just merged another PR for French a couple of days ago. Here is the commit https://github.com/ddnexus/pagy/pull/154/commits/cf425d8b81056b1088fbd57871602d5e21c82de1.
I notice that they use different terms, and my French is not good enough to understand which one would be better.

Could you give me your feedback? Thanks!

**Comment by ddnexus** [comment]
It looks like your translation is closer to the original en text.

**Comment by czj** [comment]
Sorry, I did not see the PR.

Our PR is indeed written in a less "natural" french langage.
We had less experience with Pagy usage/location of messages.

Thanks to https://github.com/MrMoins for the translations !

**Comment by ddnexus** [comment]
Wait. Are you saying that yours is less natural? I actually thought otherwise. To me it looked like it was more consistent with Pagy. Now I am confused. :/

**Comment by czj** [comment]
You are right, in both sentences :-)

- my translation is closer to Pagy’s « technical » terms, because you use the word « item » which translates as « élément »
- his translation is closer to usual terms in french langage : there’s often « search results » that translates to « résultats de recherche »

Depends on what you prefer using !

**Comment by ddnexus** [comment]
Thanks for the explanation... 

then since a list may also be something not related to a search, I think that a more generic élément could be more consistent with both a result from a search or a simple listing (so résultat seems more weird unless you did search). What do you think?

What about "Affichage" and "Afficher" that are missing in the other translation? That is what made me think that is more close to convey the same meaning than in English, but I would like to know what you think about that too.

**Comment by czj** [comment]
> then since a list may also be something not related to a search, I think that a more generic élément could be more consistent with both a result from a search or a simple listing (so résultat seems more weird unless you did search). What do you think?

I agree, a more generic term works better (that's why you had it in English I presume)

> What about "Affichage" and "Afficher" that are missing in the other translation? That is what made me think that is more close to convey the same meaning than in English, but I would like to know what you think about that too.

"Affichage" can be translated a "the display of" more than "displaying" (that's a French specific way of "stating".

"Afficher" is the verb. "Afficher 50 éléments" would be a short / imperative version of "Je voudrais afficher 50 éléments". (which is never used). It's giving the order to "display 50 items".

I see you have used my translation in 3.0 :-) Thanks.

**Comment by ddnexus** [comment]
> I see you have used my translation in 3.0 :-) Thanks.

Thank you for the PR and for the explanations. The other translation is OK too, just a bit too specific to be used as the generic default IMO. Anyway, everybody can easily change it as it prefers, so it is not a concern.

**Pull request closed without merging**
