### PR TITLE
Add ckb: "pagination" entry

### PR DESCRIPTION
**Pull request by muhammadnawzad**

### CODE REVIEW

**Comment by benkoshy** [comment]
[muhammadnawzad](https://github.com/muhammadnawzad) thanks for the patch! 

(There is some refactoring occurring in the dev branch. We'll merge after the refactoring has finished - I beg your patience till then  🙏🙏.)

**Comment by ddnexus** [comment]
Thank you @muhammadnawzad.

We are very close to release the v7.0.0 that will be ARIA compliant and will have a slightly different structure for the dictionary files.

We will definitely use your PR as-is for the version 6.4.5, but we need also the new version for version 7.0.0

Editing your `ckb.yml` file it would look like the following:

```yml
ckb:
  pagy:
    aria_label:
      nav: "Pages"
      prev: "پاش"
      next: "پێش"
    prev: "&lt;"
    next: "&gt;"
    gap: "&hellip;"
    item_name: "بابەت"
    info:
      no_items: "هیچ %{item_name}ێک نەدۆزرایەوە"
      single_page: "پیشاندانی <b>%{count}</b> %{item_name}"
      multiple_pages: "پشاندانی %{item_name}ی <b>%{from}-%{to}</b> لە کۆی <b>%{count}</b> بە گشتی"
    combo_nav_js: "<label>پەڕی %{page_input} لە %{pages}</label>"
    items_selector_js: "<label>نیشاندانی %{items_input} %{item_name} لە هەر پەڕێک</label>"
```

As you can see there is a new `pagy.aria_label.nav` entry that requires your kind translation too.

Please, could you post here the word "Pages" properly translated? We will then do the necessary changes right in the new version, no need for another PR.

Thank you!

**Comment by muhammadnawzad** [comment]
Hello @ddnexus, thank you for the fast response and review.

The translation for `"Pages"` would be `"پەڕەکان"` and here is what the ckb.yml file would look like.

```
# :other pluralization (see https://github.com/ddnexus/pagy/blob/master/lib/pagy/i18n.rb)

ckb:
  pagy:
    item_name: "بابەت"
    aria_label:
      nav: "پەڕەکان"
      prev: "پاش"
      next: "پێش"
    prev: "&lt;"
    next: "&gt;"
    gap: "&hellip;"    
    info:
      no_items: "هیچ %{item_name}ێک نەدۆزرایەوە"
      single_page: "پیشاندانی <b>%{count}</b> %{item_name}"
      multiple_pages: "پشاندانی %{item_name}ی <b>%{from}-%{to}</b> لە کۆی <b>%{count}</b> بە گشتی"
    combo_nav_js: "<label>پەڕی %{page_input} لە %{pages}</label>"
    items_selector_js: "<label>نیشاندانی %{items_input} %{item_name} لە هەر پەڕێک</label>"
```

Please let me know if another PR is needed, or I should commit the changes. Thank you.

**Comment by ddnexus** [comment]
@muhammadnawzad thank you!

> Please let me know if another PR is needed, or I should commit the changes. Thank you.

It's not technically needed (what was absolutely needed was your translation), but if you prefer to write another PR (good for contributions!), adding the new format/translation that you posted above please, base it on the [dev](https://github.com/ddnexus/pagy/tree/dev) branch.

Thank you!

**Pull request merged**
