### PR TITLE
Bulma extra

### PR DESCRIPTION
**Pull request by enzinia**
According to #56.

Added extra for Bulma CSS Framework.

All templates and helper was tested on real Bulma project.

### CODE REVIEW

**Comment by ddnexus** [comment]
@enzinia Amazing job! Thank you!

Would you be interested in adding also a `pagy_compact_bulma` and `pagy_reponsive_bulma` helpers taken from the bootstrap version, but with the proper classes replaced?

**Comment by enzinia** [comment]
@ddnexus sure, it can be useful.

What about to add it in separated PR?

**Comment by ddnexus** [comment]
it is actually all about bulma, so better here. Thanks.

**Comment by enzinia** [comment]
Here we go, added bulma helpers for `compact` and `responsive` extras.

Compact one was a little tricky, but I managed to do this in Bulma way.

There is how it looks:
bulma_compact


Please tell me, if I need to squash commits.

**Comment by ddnexus** [comment]
Great job. Thank you!

**Comment by ddnexus** [comment]
@enzinia 
Hi I fixed quite a few typos in the PR ("area" used in place of "aria" in helpers and tests), then I refactored the `pagy_nav_bulma` as a single method, since the provate method was not called by any other methods.

Then I refactored also the responsive helpers so they can all be more consistent across implementations.

Please, could you test the final result in the `dev` branch? If everything will be ok, I will merge it in master and push to rubygems. Thanksd

**Comment by enzinia** [comment]
@ddnexus 
Oh, so sorry for this ridiculous typos. Please fix it also in templates.

Rechecked all Bulma helpers and templates (just in case) from `dev` branch. All looks good to me, doesn't see any problems.

Also can confirm that Turbolinks issue fixed, there is no errors now.

**Comment by ddnexus** [comment]
I totally missed to check the templates. Fixed. Thanks.

**Pull request merged**
