### PR TITLE
Docs: explain: pagy + retype, add contribution instructions

### PR DESCRIPTION
**Pull request by benkoshy**
Why? To document hidden steps - without which it might be difficult for someone to piece it altogether. also to lower the barrier to contributing to the docs.

### CODE REVIEW

**Comment by ddnexus** [comment]
Thank you @benkoshy. A reference to doc on doc was missing, so it's a very useful addition, however I would reduce it to a single point in the list under the contributions section in the README.

If more content is really needed, please point a link to a new doc page or section, so the README will remain mostly a pointer.

Thank you!

**Comment by benkoshy** [comment]
> Thank you @benkoshy. A reference to doc on doc was missing, so it's a very useful addition, however I would reduce it to a single point in the list under the contributions section in the README. (Something like "- For doc contributions ..."
> 
> If more content is really needed, please point a link to a new doc page or section, so the README will remain mostly a pointer.
> 
> Thank you!

* I have removed the section and added a link
* I have also removed the page from the retype docs. I figure it can safely be exluded without cluttering - but those who want to find it will easily see it via the link, or it will be obvious in the `docs` folder.

**Comment by ddnexus** [comment]
@benkoshy I didn't lock the rubocop version in the CI Gemfile, so the CI will always use the latest, despite the one locked in the repo Gemfile.lock.

That way we are forced to notice that we should update gems and javascript modules, in order to keep the page environment always up-to-date.

**Comment by ddnexus** [comment]
@dependabot rebase

**Comment by benkoshy** [comment]
> @benkoshy I didn't lock the rubocop version in the CI Gemfile, so the CI will always use the latest, despite the one locked in the repo Gemfile.lock.
> 
> That way we are forced to notice that we should update gems and javascript modules, in order to keep the pagy environment always up-to-date.

 Should I update pagy to comply with rubocop? Am i understanding the implications of the above correctly?

**Comment by ddnexus** [comment]
It's done. If you rebase your PR on master it should pass. :crossed_fingers:

**Comment by benkoshy** [comment]
Force pushed after rebasing. 

If you're happy: squash + merge?

**Pull request merged**
