### PR TITLE
fix: foundation combo helper

### PR DESCRIPTION
**Pull request by benkoshy**
### What is this PR?

A fix for the problems found in:  #465

### What was changed?

The styling of the foundation combo nav helper.

**Admin note:** This branch has been rebased on top of `ddnexus/dev` and I forced pushed.

### CODE REVIEW

**Comment by ddnexus** [comment]
@benkoshy: I guess it works as expected in your app, right?

**Comment by benkoshy** [comment]
Now that you ask,  just maybe i might not have x2 checked.  I'll make 100% sure tomorrow.  Sorry about the uncertainty

**Comment by ddnexus** [comment]
No prob.

The reason is that rematch and snapshots have ultra fast updating, but need manual check of the actual working output.

**Comment by benkoshy** [comment]
looks good to me: works like a charm:

Looks good to me

**Comment by ddnexus** [comment]
Thank you!

**Pull request merged**
