### PR TITLE
Allowing users to override the request path - V6

### PR DESCRIPTION
**Pull request by elliotlarson**
PR #403 code on top of the V6 branch

### CODE REVIEW

**Comment by elliotlarson** [comment]
@ddnexus Do you want me to squash these commits?

**Comment by ddnexus** [comment]
@elliotlarson Thank you for your fast action and sorry for the lack of feedback on my side. I am in a loooong month and quite overwhelmed by too many new things...

The PR passed the tests, so it is formally OK, however I need a few more days to find some time for it.
Thanks

**Comment by elliotlarson** [comment]
@ddnexus Oh, no worries.  Sounds good 👍

**Comment by ddnexus** [comment]
@elliotlarson I refactored the v6 branch and it results in a big mess with this PR. If you could create a new PR, adding your commits on top of v6, everything should be cleaner. Thank you.

**Comment by elliotlarson** [comment]
@ddnexus Okay, cool.  I'll work on that.

**Comment by ddnexus** [comment]
> @ddnexus Oh, no worries. Sounds good 👍

While at it, I didn't find the entry of the new variable in the pagy.rb initializer. Please, could you check that?

**Comment by ddnexus** [comment]
@elliotlarson Thank you. I had a bit of time and I edited it. (6e939a01)

**Pull request closed without merging**
