### PR TITLE
[Enhance] Freeze Some Class Immutable Constant Variables

### PR DESCRIPTION
**Pull request by berniechiu**
### Objective

Further increase speed and reduce memory usage through mapping and remove extra conditions, haven't rerun the benchmark yet lol. Hope this PR helps : )

### Features
- reduce extra conditional
- use mapping

### CODE REVIEW

**Comment by ddnexus** [comment]
Thanks @berniechiu, 

IIRC, freezing that constants didn't change the number of objects reported in the [Memory Objects Details section](https://ddnexus.github.io/pagination-comparison/gems.html?page=20#pmemory)(please click on the Details section to open it), but I didn't have time to investigate it further. Also, I believe I did some benchmark using something like `hash = Hash.new{...}` and `hash[c]` but IIRC it was slower than `&&`and `||`, but I would like to try it all again to be sure.

Thanks again for your PR and good spirit :)
We should do some benchmark and profile on the specific lines in order to decide. ;)

**Comment by berniechiu** [comment]
Cool, will comback later with a more precise benchmark

**Comment by ddnexus** [comment]
@berniechiu: Kudos! 
The array trick improves the proc by ~23%! That's great! Thank you! 

```ruby
Benchmark.ips do |x|
  x.config(:stats => :bootstrap)

  old_plurals = -> (c) {c==0 && 'zero' || c==1 && 'one' || 'other'}.freeze

  x.report('old_conditions') do
    old_plurals.call(0)
    old_plurals.call(1)
    old_plurals.call(2)
  end

  hash = Hash.new{|h,k| 'other' if k>1 }.merge!(0=>'zero', 1=>'one')

  new_plurals = -> (c) {hash[c]}

  x.report('hash') do
    new_plurals.call(0)
    new_plurals.call(1)
    new_plurals.call(2)
  end


  types   = ['zero', 'one'].freeze
  plurals = -> (c) {types[c] || 'other'}

  x.report('array') do
    plurals.call(0)
    plurals.call(1)
    plurals.call(2)
  end

  x.compare!
end
```

```
Warming up --------------------------------------
      old_conditions   204.018k i/100ms
                hash   205.140k i/100ms
               array   242.331k i/100ms
Calculating -------------------------------------
      old_conditions      2.966M (± 0.4%) i/s -     14.893M in   5.022541s
                hash      2.895M (± 0.5%) i/s -     14.565M in   5.033568s
               array      3.639M (± 1.1%) i/s -     18.175M in   5.012356s
                   with 95.0% confidence

Comparison:
               array:  3639031.0 i/s
      old_conditions:  2966352.8 i/s - 1.23x  (± 0.01) slower
                hash:  2894713.2 i/s - 1.26x  (± 0.02) slower
                   with 95.0% confidence
```

**Comment by berniechiu** [comment]
Thanks! @ddnexus

**Pull request merged**
