### PR TITLE
Cursor paginate

### PR DESCRIPTION
**Pull request by Uysim**
Add cursor paginate that support only ActiveRecord

What is cursor paginate? [Offset and Cursor](https://dev.to/jackmarchant/offset-and-cursor-pagination-explained-b89)

****Current Support***: cursor_paginate for ['sequence', 'uuid'], has_more?

***Test***: Coming (need to integrate with ActiveRecord) (need help) 
***Doc***: Coming
***Custom Order***: After this is a good idea
***Note***: Open for any suggestion

### CODE REVIEW

**Comment by ddnexus** [comment]
This looks very promising! I will probably have some time to look into it during the weekend. Thank you!

**Comment by joshm1204** [comment]
Has keyset pagination been merged yet? If not why not?

**Comment by ddnexus** [comment]
Hi Uysim, I thought you were going to add documentation and tests. 
Without that, the PR has to be considered as alpha or beta software, hence not yet ready to merge.

**Comment by espen** [comment]
btw, related: https://github.com/afair/postgresql_cursor

**Comment by Uysim** [comment]
@espen  feel like it work only for serial. If it is uuid i won't work right?

**Comment by espen** [comment]
@Uysim I haven't tried it but it looks like it will use a cursor to paginate whatever query you give it.

**Comment by Uysim** [comment]
@espen  maybe the same. But not for UUID

**Comment by Uysim** [comment]
Hi. When I tried add the test for this feature. I will like it will make with gem heavier with active record. So I decide you move it my own gem which is depend on pagy. https://github.com/Uysim/pagy-cursor
If you come along this. Please take a look and give me some feedback

**Pull request closed without merging**
