### PR TITLE
Extras for Meilisearch

### PR DESCRIPTION
**Pull request by molfar**
I've added  extras for pagination Meilisearch results https://github.com/meilisearch/meilisearch-rails

### CODE REVIEW

**Comment by ddnexus** [comment]
Thank you!
It looks like it is only missing the documentation.

**Comment by benkoshy** [comment]
@ddnexus Hi Domizio

You've made allusion to a sample branch being made for Meilisearch on the demo app:

image

...but now the extra has been written. 

Did you want a meilisearch branch on the sample rails app?

**Comment by ddnexus** [comment]
@benkoshy an extra branch is not technically needed anymore, since the extra implements the same logic of searchkick (just a bit simpler). Thanks.

**Comment by molfar** [comment]
@ddnexus I tried to create docs, bu something went wrong with git commiting. I have no mind why there are 2 doc commits, and even one merge. Could you help to fix it? Moreover, I based my work on wrong branch, master instead of dev. So you commit 1c3d283 also get stacked with this PR. I dont know how to figure out with all this stuff)

**Comment by ddnexus** [comment]
@molfar the cleanest/easiest way to fix a messed up PR is creating a new branch on top to `dev`, cherry pick your commits one by one starting from the oldest (and eventually squash/fix some of them if that makes more sense to you) into the new branch. Then create a PR for the new branch and close the old PR (this one).

**Review by ddnexus — COMMENTED** [review]
Only minor remarks about the changed files

**Comment by molfar** [comment]
Close this PR in favor to https://github.com/ddnexus/pagy/pull/316

**Pull request closed without merging**
