### PR TITLE
Update example pagy.rb

### PR DESCRIPTION
**Pull request by rafaeelaudibert**
Every extra has its own 'require' line of code, except for the Overflow one, so this PR has the intention to:

Add missing "require 'pagy/extras/overflow'" line of code, to improve beginners usage

### CODE REVIEW

**Comment by rafaeelaudibert** [comment]
Excelent job with the gem, btw :smiley:

**Comment by ddnexus** [comment]
Good catch! I cannot believe I missed that for so long :)

**Comment by rafaeelaudibert** [comment]
I must admit it was kinda hidden, as I just noted it when I needed to use it by myself, hahah
I tried to verify all the other 'requires' and they all seem to be there

**Comment by rafaeelaudibert** [comment]
Went through the code and also found a typo on the pt-br.yml file.

**Comment by ddnexus** [comment]
Thanks also for that. I will better wait a bit more before merging so you can catch more glitches ;)

**Pull request merged**
