### PR TITLE
Elasticsearch Rails extra

### PR DESCRIPTION
**Pull request by renshuki**
Hi,

Here is my little contribution for [`elasticsearch-rails` gem](https://github.com/elastic/elasticsearch-rails) support as an extra for Pagy.

Changes include:
- Creation of a new Pagy extra to pagiante `elasticsearch-rails` gem results
- Adding basic tests for the extra
- Update the documentation accordingly

Let me know what you think about it.

Thanks 😄

### CODE REVIEW

**Comment by ddnexus** [comment]
Thank you for your PR, and sorry for the late answer. 

Please, rename `elasticsearch-rails` to `elasticsearch_rails` everywhere it appears (consistently to the "out_of_range" extra which use the underscores).

Please, re-order `elasticsearch_rails` in alpha order in the list of extras and in the doc menu.

Thanks

**Comment by renshuki** [comment]
Done 😃 
Let me know if you catch anything else.

**Comment by ddnexus** [comment]
Thank you!

**Comment by renshuki** [comment]
Thank you for the merge (and the fix for rubocop offenses) 👍

**Pull request merged**
