### PR TITLE
Docs: add quotes around turbolinks:load

### PR DESCRIPTION
**Pull request by creativetags**

### CODE REVIEW

**Comment by benkoshy** [comment]
@dependabot rebase

**Comment by benkoshy** [comment]
Thanks for the patch!

**Comment by benkoshy** [comment]
@creativetags: if you are interested in PRs for the rest of the turbolinks event handlers: have at it! if not i'll put in the PR with the credit towards you referring to this PR. thanks for your contribution.

**Comment by creativetags** [comment]
Thanks!

**Pull request merged**
