### PR TITLE
Add term default value for case when term not passed

### PR DESCRIPTION
**Pull request by bestwebua**
Add the same behaviour like in ```Searchkick.searchkick_search``` for ```term``` default value.

### CODE REVIEW

**Comment by ddnexus** [comment]
Thank you for the PR!

I refactored it in a different way that has a few advantages compared to adding a forced `'*'` as a term.

The refactoring is more agnostic of the way searchkick (and elasticsearch_rails) work. The only assumption is that there must be a last argument that must be a hash (which is what pagy use as the options), so it would modify less the original passed arguments. 

For example: if you pass a single hash it will still pass a single hash to the search method (adding the pagination options to it), so it should be a bit more robust in case of upstream changes.

I also added a few tests to cover the optional term argument.

Please, can you try it (dev branch). Thanks.

**Comment by bestwebua** [comment]
Hi, Domizio! Works like a charm! I have checked with tems parameter and without it. As expected, the output results were the same :+1:

**Comment by ddnexus** [comment]
@bestwebua thank you for your help!

Pushed to rubygem as version 3.4.1.

**Comment by bestwebua** [comment]
Thank you, bro!

**Pull request closed without merging**
